DEP Upgrade frotnend build stack
silverstripe/silverstripe-comments pull request #358
Opened 2023-01-20 02:43 UTC by GuySartorelli

**DO NOT SQUASH** - the commits in this PR are distinct.

## Parent issue
- https://github.com/silverstripeltd/product-issues/issues/644

2023-01-26 02:14 UTC, GuySartorelli commented
unit test failure is unrelated

2023-01-26 02:15 UTC, GuySartorelli commented on .eslintignore
> -client/src/legacy/
It's not _actually_ legacy - we're not getting rid of it any time soon so it should meet our linting standards.

2023-01-30 23:48 UTC, emteknetnz requested changes
Got this javascript error when manually testing ticking a submitted comment in the comments tab and then select 'Approve' from the dropdown

![image](https://user-images.githubusercontent.com/4809037/215622650-0107c06d-dc0a-46fe-b3d3-05e26853e325.png)

2023-02-01 01:42 UTC, GuySartorelli commented
The comments form currently isn't rendering - https://github.com/silverstripe/silverstripe-framework/pull/10676 needs to be merged to fix that.

2023-02-01 01:56 UTC, GuySartorelli commented
Email address validation also broken - https://github.com/silverstripe/comment-notifications/pull/50 fixes that

2023-02-01 02:31 UTC, GuySartorelli commented
The error you mentioned is now fixed in the bulk editing tools PR

2023-02-01 21:05 UTC, emteknetnz approved these changes

2023-02-01 21:05 UTC, merged