MNT Broken builds
silverstripe/silverstripe-comments pull request #360
Opened 2023-01-24 02:43 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/659

2023-01-24 23:45 UTC, GuySartorelli requested changes
This broke because of https://github.com/silverstripe/silverstripe-framework/pull/10538
Use `Controller::normaliseTrailingSlash()` to protect against future config changes.

2023-01-24 23:50 UTC, emteknetnz commented
Changes to this where in a unit test and our default in no trailing slash, so I think it's correct to hardcode the unit test for no slash

2023-01-25 00:38 UTC, GuySartorelli commented
While I do think what I've recommended is best practice, after an offline conversation I'll just merge this as-is. We can deal with best practices some time later.

2023-01-25 00:38 UTC, GuySartorelli approved these changes

2023-01-25 00:38 UTC, merged